import { describe, expect, it } from 'bun:test';

import { makeRCVersionManager } from '../src/versioning';

import { createMockVcs } from './utils/vcs';

describe('RC Version Manager', () => {
  const mockVcs = createMockVcs();

  it('should initialize correctly in RC mode by default', () => {
    const vm = makeRCVersionManager(mockVcs);
    expect(vm.isRCMode).toBeTrue();
  });

  it('should append -rc.0 to normal version', () => {
    const vm = makeRCVersionManager(mockVcs);
    expect(vm.bumpVersion('1.0.0', 'patch')).toBe('1.0.1-rc.0');
    expect(vm.bumpVersion('2.1.3', 'minor')).toBe('2.2.0-rc.0');
    expect(vm.bumpVersion('0.4.0', 'major')).toBe('1.0.0-rc.0');
  });

  it('should increment existing rc versions', () => {
    const vm = makeRCVersionManager(mockVcs);
    expect(vm.bumpVersion('1.0.0-rc.0', 'patch')).toBe('1.0.0-rc.1');
    expect(vm.bumpVersion('1.0.0-rc.5', 'minor')).toBe('1.0.0-rc.6');
  });

  it('should use custom rc identifier', () => {
    const vm = makeRCVersionManager(mockVcs, { rcIdentifier: 'beta' });
    expect(vm.bumpVersion('1.0.0', 'minor')).toBe('1.1.0-beta.0');
    expect(vm.bumpVersion('1.0.0-beta.0', 'patch')).toBe('1.0.0-beta.1');
  });

  it('should reset rc if rc identifier changes or mismatches', () => {
    const vm = makeRCVersionManager(mockVcs, { rcIdentifier: 'rc' });
    expect(vm.bumpVersion('1.0.0-beta.1', 'minor')).toBe('1.0.0-rc.0');
  });

  it('should not bump when size is skip', () => {
    const vm = makeRCVersionManager(mockVcs);
    expect(vm.bumpVersion('1.0.0', 'skip')).toBe('1.0.0');
    expect(vm.bumpVersion('1.0.0-rc.2', 'skip')).toBe('1.0.0-rc.2');
  });

  it('Scenario 1: progressive RC bumps and transition to stable', () => {
    const rcManager = makeRCVersionManager(mockVcs, { upgradeReady: false });
    const releaseManager = makeRCVersionManager(mockVcs, { upgradeReady: true });

    const step1 = rcManager.bumpVersion('0.0.1', 'minor');
    expect(step1).toBe('0.1.0-rc.0');

    const step2 = rcManager.bumpVersion('0.1.0-rc.0', 'patch');
    expect(step2).toBe('0.1.0-rc.1');

    const step3 = rcManager.bumpVersion('0.1.0-rc.1', 'major');
    expect(step3).toBe('1.0.0-rc.0');

    const step4 = releaseManager.bumpVersion('1.0.0-rc.0', 'major');
    expect(step4).toBe('1.0.0');
  });

  it('Scenario 2: minor RC bump and transition to stable major', () => {
    const rcManager = makeRCVersionManager(mockVcs, { upgradeReady: false });
    const releaseManager = makeRCVersionManager(mockVcs, { upgradeReady: true });

    const step1 = rcManager.bumpVersion('0.0.1', 'minor');
    expect(step1).toBe('0.1.0-rc.0');

    const step2 = releaseManager.bumpVersion('0.1.0-rc.0', 'major');
    expect(step2).toBe('1.0.0');
  });

  it('should fallback to standard mode when upgradeReady is true', () => {
    const vm = makeRCVersionManager(mockVcs, { upgradeReady: true });
    expect(vm.isRCMode).toBeFalse();
  });

  it('Verification: pre-release tags should not be generated by default', () => {
    const rcManagerDefault = makeRCVersionManager(mockVcs, { upgradeReady: false });
    expect(rcManagerDefault.shouldTag('1.1.0-rc.0')).toBe(false);
    expect(rcManagerDefault.shouldTag('1.1.0')).toBe(true);

    const rcManagerWithTags = makeRCVersionManager(mockVcs, { upgradeReady: false, tagPrereleases: true });
    expect(rcManagerWithTags.shouldTag('1.1.0-rc.0')).toBe(true);
    expect(rcManagerWithTags.shouldTag('1.1.0')).toBe(true);
  });
});
