export const getIconForFile = (filename: string): string => {
  const lowercaseName = filename.toLowerCase();

  const exactMatch = getExactMatch(lowercaseName);
  if (exactMatch !== undefined) {
    return exactMatch;
  }

  const suffixMatch = getSpecialSuffixMatch(lowercaseName);
  if (suffixMatch !== undefined) {
    return suffixMatch;
  }

  // Mimics Rust's `name.split('.').next_back().unwrap_or("")`
  const parts = filename.split('.');
  const ext = parts.length > 0 ? parts[parts.length - 1] : '';

  return getExtensionMatch((ext ?? '').toLowerCase());
};

const getExactMatch = (name: string): string | undefined => {
  switch (name) {
    case '.babelrc':
      return '';
    case '.bash_profile':
    case '.bashrc':
    case '.zprofile':
    case '.zshenv':
    case '.zshrc':
      return '';
    case '.dockerignore':
    case 'containerfile':
    case 'dockerfile':
    case 'docker-compose.yaml':
    case 'docker-compose.yml':
    case 'compose.yaml':
    case 'compose.yml':
      return '󰡨';
    case '.ds_store':
    case '.gitconfig':
    case '.luaurc':
      return '';
    case '.editorconfig':
      return '';
    case '.env':
    case 'env':
      return '';
    case '.eslintrc':
    case '.eslintignore':
    case 'eslint.config.cjs':
    case 'eslint.config.js':
    case 'eslint.config.mjs':
    case 'eslint.config.ts':
      return '';
    case '.git-blame-ignore-revs':
    case '.gitattributes':
    case '.gitignore':
    case '.gitmodules':
    case 'commit_editmsg':
      return '';
    case '.gitlab-ci.yml':
      return '';
    case '.gtkrc-2.0':
    case 'gtkrc':
      return '';
    case '.gvimrc':
    case '.vimrc':
    case '_gvimrc':
    case '_vimrc':
      return '';
    case '.justfile':
    case 'justfile':
      return '';
    case '.mailmap':
      return '󰊢';
    case '.npmignore':
    case '.npmrc':
      return '';
    case '.nuxtrc':
      return '󱄆';
    case '.nvmrc':
      return '';
    case '.prettierrc':
    case '.prettierrc.json':
    case '.prettierrc.json5':
    case '.prettierrc.toml':
    case '.prettierrc.yaml':
    case '.prettierrc.yml':
    case '.prettierignore':
    case 'prettier.config.js':
    case 'prettier.config.cjs':
    case 'prettier.config.mjs':
    case 'prettier.config.ts':
      return '';
    case '.settings.json':
      return '';
    case '.srcinfo':
    case '.SRCINFO':
      return '󰣇';
    case '.xauthority':
    case '.xinitrc':
    case '.xresources':
    case '.xsession':
    case 'xorg.conf':
    case 'xsettingsd.conf':
      return '';
    case 'brewfile':
    case 'gemfile$':
      return '';
    case 'bspwmrc':
    case 'sxhkdrc':
      return '';
    case 'build':
    case 'bazel':
    case 'bzl':
    case 'workspace':
      return '';
    case 'build.gradle':
    case 'gradlew':
    case 'gradle.properties':
    case 'gradle-wrapper.properties':
      return '';
    case 'build.zig.zon':
      return '';
    case 'checkhealth':
      return '󰓙';
    case 'cmakelists.txt':
    case 'config':
    case 'cmake':
      return '';
    case 'code_of_conduct':
    case 'code_of_conduct.md':
      return '';
    case 'commitlint.config.js':
    case 'commitlint.config.ts':
      return '󰜘';
    case 'copying':
    case 'copying.lesser':
      return '';
    case 'ext_typoscript_setup.txt':
      return '';
    case 'favicon.ico':
      return '';
    case 'fp-info-cache':
    case 'fp-lib-table':
    case 'sym-lib-table':
      return '';
    case 'freecad.conf':
    case 'FreeCAD.conf':
      return '';
    case 'gnumakefile':
    case 'makefile':
      return '';
    case 'go.mod':
    case 'go.sum':
    case 'go.work':
      return '';
    case 'gruntfile.babel.js':
    case 'gruntfile.coffee':
    case 'gruntfile.js':
    case 'gruntfile.ts':
      return '';
    case 'gulpfile.babel.js':
    case 'gulpfile.coffee':
    case 'gulpfile.js':
    case 'gulpfile.ts':
      return '';
    case 'hypridle.conf':
    case 'hyprland.conf':
    case 'hyprlock.conf':
      return '';
    case 'i18n.config.js':
    case 'i18n.config.ts':
      return '󰗊';
    case 'i3blocks.conf':
    case 'i3status.conf':
      return '';
    case 'ionic.config.json':
      return '';
    case 'cantorrc':
    case 'kalgebrarc':
    case 'kdeglobals':
      return '';
    case 'kdenlive-layoutsrc':
    case 'kdenliverc':
      return '';
    case 'kritadisplayrc':
    case 'kritarc':
      return '';
    case 'license':
    case 'license.md':
      return '';
    case 'lxde-rc.xml':
      return '';
    case 'lxqt.conf':
      return '';
    case 'mix.lock':
      return '';
    case 'mpv.conf':
      return '';
    case 'node_modules':
      return '';
    case 'nuxt.config.cjs':
    case 'nuxt.config.js':
    case 'nuxt.config.mjs':
    case 'nuxt.config.ts':
      return '󱄆';
    case 'package.json':
    case 'package-lock.json':
      return '';
    case 'pkgbuild':
    case 'PKGBUILD':
      return '';
    case 'platformio.ini':
      return '';
    case 'pom.xml':
      return '';
    case 'procfile':
      return '';
    case 'prusaslicer.ini':
    case 'PrusaSlicer.ini':
    case 'prusaslicergcodeviewer.ini':
    case 'PrusaSlicerGcodeViewer.ini':
      return '';
    case 'py.typed':
      return '';
    case 'qtproject.conf':
    case 'QtProject.conf':
      return '';
    case 'rakefile':
      return '';
    case 'robots.txt':
      return '󰚩';
    case 'security':
    case 'security.md':
      return '󰒃';
    case 'settings.gradle':
      return '';
    case 'svelte.config.js':
      return '';
    case 'unlicense':
      return '';
    case 'vagrantfile$':
      return '';
    case 'vlcrc':
      return '󰕼';
    case 'vercel.json':
      return '▲';
    case 'webpack':
      return '󰜫';
    case 'weston.ini':
      return '';
    default:
      return undefined;
  }
};

const getSpecialSuffixMatch = (name: string): string | undefined => {
  if (
    name.endsWith('.spec.js') ||
    name.endsWith('.spec.jsx') ||
    name.endsWith('.spec.ts') ||
    name.endsWith('.spec.tsx') ||
    name.endsWith('.test.js') ||
    name.endsWith('.test.jsx') ||
    name.endsWith('.test.ts') ||
    name.endsWith('.test.tsx')
  ) {
    return '';
  }
  return undefined;
};

const getExtensionMatch = (ext: string): string => {
  switch (ext) {
    // Source/Programming Languages
    case 'rs':
      return '';
    case 'rlib':
      return '';
    case 'c':
    case 'm':
      return '';
    case 'c++':
    case 'cc':
    case 'ccm':
    case 'cp':
    case 'cpp':
    case 'cppm':
    case 'cxx':
    case 'cxxm':
    case 'mm':
    case 'mpp':
    case 'ixx':
      return '';
    case 'cs':
      return '󰌛';
    case 'java':
      return '';
    case 'kt':
    case 'kts':
      return '';
    case 'swift':
    case 'xcplayground':
      return '';
    case 'go':
      return '';
    case 'zig':
      return '';
    case 'nim':
      return '';
    case 'nix':
      return '';
    case 'scala':
    case 'sbt':
    case 'sc':
      return '';
    case 'lua':
    case 'luac':
    case 'luau':
      return '';
    case 'php':
      return '';
    case 'pl':
    case 'pm':
    case 't':
      return '';
    case 'rb':
    case 'rake':
      return '';
    case 'ex':
    case 'exs':
    case 'eex':
    case 'heex':
    case 'leex':
      return '';
    case 'erl':
    case 'hrl':
      return '';
    case 'clj':
    case 'cljc':
      return '';
    case 'cljs':
    case 'cljd':
    case 'edn':
      return '';
    case 'fs':
    case 'fsi':
    case 'fsscript':
    case 'fsx':
    case 'f#':
      return '';
    case 'hs':
    case 'lhs':
      return '';
    case 'ml':
    case 'mli':
      return '';
    case 'sml':
    case 'sig':
    case 'signature':
      return 'λ';
    case 'el':
    case 'elc':
    case 'eln':
      return '';
    case 'apl':
      return '⍝';
    case 'bqn':
      return '⎉';
    case 'elm':
      return '';
    case 'gleam':
      return '';
    case 'vala':
      return '';
    case 'sol':
      return '';
    case 'hx':
      return '';
    case 'mojo':
    case '🔥':
      return '';
    case 'fnl':
      return '';
    case 'nu':
      return '>';
    case 'org':
      return '';
    case 'scm':
      return '󰘧';
    case 'f90':
      return '󱈚';
    case 'r':
      return '󰟔';
    case 'groovy':
      return '';

    // Python Family
    case 'py':
    case 'pyc':
    case 'pyd':
    case 'pyi':
    case 'pyo':
    case 'pyw':
    case 'pyx':
    case 'ipynb':
    case 'pxd':
    case 'pxi':
      return '';

    // Scripting & Terminal
    case 'sh':
    case 'bash':
    case 'zsh':
    case 'fish':
    case 'csh':
    case 'ksh':
    case 'awk':
      return '';
    case 'bat':
      return '';
    case 'ps1':
    case 'psd1':
    case 'psm1':
      return '󰨊';
    case 'tcl':
    case 'tbc':
      return '󰛓';
    case 'azcli':
      return '';
    case 'x':
    case 'xm':
      return '';

    // Web Development
    case 'js':
    case 'cjs':
    case 'mjs':
      return '';
    case 'ts':
    case 'cts':
    case 'mts':
    case 'd.ts':
      return '';
    case 'jsx':
      return '';
    case 'tsx':
      return '';
    case 'vue':
      return '';
    case 'svelte':
      return '';
    case 'astro':
      return '';
    case 'html':
      return '';
    case 'htm':
      return '';
    case 'css':
      return '';
    case 'sass':
    case 'scss':
      return '';
    case 'less':
      return '';
    case 'styl':
      return '';
    case 'liquid':
      return '';
    case 'templ':
      return '';

    // Data / Config / Markup
    case 'json':
    case 'json5':
    case 'jsonc':
    case 'cson':
    case 'webmanifest':
    case 'nswag':
      return '';
    case 'toml':
      return '';
    case 'yaml':
    case 'yml':
    case 'cfg':
    case 'conf':
    case 'ini':
      return '';
    case 'xml':
    case 'xaml':
      return '󰗀';
    case 'csv':
      return '';
    case 'tf':
      return '';
    case 'tfvars':
      return '';
    case 'bib':
      return '󱉟';
    case 'tex':
      return '';
    case 'tsconfig':
      return '';

    // Compiled Binaries & Libraries
    case 'o':
    case 'out':
    case 'bin':
    case 'elf':
    case 'exe':
    case 'app':
      return '';
    case 'so':
    case 'a':
    case 'ko':
    case 'dll':
    case 'lib':
      return '';
    case 'wasm':
      return '';

    // Document formats
    case 'txt':
      return '󰈙';
    case 'pdf':
      return '';
    case 'doc':
    case 'docx':
      return '󰈬';
    case 'xls':
    case 'xlsx':
      return '󰈛';
    case 'ppt':
      return '󰈧';
    case 'epub':
    case 'mobi':
    case 'ebook':
      return '';
    case 'markdown':
    case 'md':
    case 'mdx':
    case 'rmd':
      return '';

    // Images & Graphics
    case 'png':
    case 'jpg':
    case 'jpeg':
    case 'gif':
    case 'bmp':
    case 'webp':
    case 'jxl':
    case 'ico':
      return '';
    case 'svg':
      return '󰜡';
    case 'ai':
      return '';
    case 'psd':
    case 'psb':
      return '';
    case 'xcf':
      return '';
    case 'image':
    case 'img':
    case 'iso':
      return '';

    // Audio & Playlists
    case 'mp3':
    case 'm4a':
    case 'wav':
    case 'flac':
    case 'ogg':
    case 'opus':
    case 'aac':
    case 'aif':
    case 'aiff':
    case 'ape':
    case 'pcm':
    case 'wma':
    case 'wv':
    case 'wvc':
      return '';
    case 'cue':
    case 'm3u':
    case 'm3u8':
    case 'pls':
      return '󰲹';

    // Video
    case 'mp4':
    case 'mkv':
    case 'mov':
    case 'webm':
    case '3gp':
    case 'm4v':
    case 'cast':
      return '';

    // Archives / Compressed
    case 'zip':
    case 'tar':
    case 'gz':
    case 'bz2':
    case 'xz':
    case '7z':
    case 'rar':
    case 'zst':
    case 'tgz':
    case 'txz':
    case 'bz':
    case 'bz3':
      return '';

    // CAD, 3D Models & Makers
    case 'dwg':
    case 'dxf':
    case 'ifc':
    case 'ige':
    case 'iges':
    case 'igs':
    case 'skp':
    case 'sldasm':
    case 'sldprt':
    case 'slvs':
    case 'ste':
    case 'step':
    case 'stp':
    case 'brep':
    case 'f3d':
      return '󰻫';
    case '3mf':
    case 'fbx':
    case 'obj':
    case 'ply':
    case 'stl':
    case 'wrl':
    case 'wrz':
      return '󰆧';
    case 'gcode':
      return '󰐫';
    case 'fcbak':
    case 'fcmacro':
    case 'fcmat':
    case 'fcparam':
    case 'fcscript':
    case 'fcstd':
    case 'fcstd1':
    case 'fctb':
    case 'fctl':
      return '';
    case 'scad':
      return '';

    // Localization & Translation
    case 'po':
    case 'pot':
    case 'qm':
    case 'strings':
    case 'xcstrings':
      return '';

    // Configuration & Package Suffixes
    case 'lock':
    case 'lck':
      return '';
    case 'log':
      return '󰌱';
    case 'bak':
      return '󰁯';
    case 'cache':
      return '';
    case 'config.ru':
      return '';
    case 'gnumakefile':
    case 'makefile':
    case 'mk':
      return '';
    case 'webpack':
      return '󰜫';

    // Fallback default file icon
    default:
      return '󰈚';
  }
};
